### ISSUE TITLE
Could you include the eclipse project file?

### ISSUE THREAD

**Issue by johnbran** [inetstd/phonegap-android-custom-splashscreen#1]
The project file seems to be missing so I cant import it into eclipse. If I try to create one from scratch there are errors. Thanks, your add in is exactly what I have been looking.

**Comment by inetstd** [comment]
Just have added.
Thank you.
Fill free to ask any question. I'm currently working with phonegap)

**Comment by johnbran** [comment]
Could you please explain how to add your plugin to eclipse? I am moving from iPhone and xcode development and I am inexperienced java and eclipse.  I finally got your project working.  For some reason mac/chrome corrupts the file during download.  It was only until I downloaded it from windows that it worked.

Thanks
John

**Comment by inetstd** [comment]
You don't need to install plugin in special way.
Please, download latest source again - I've fix my refactoring mistake (yesterday).

All you need to check that plugin was registered correctly:
go to /res/xml/plugins.xml and check your plugin name and java class name with impl:

&lt;plugin name="CustomSplashScreen" value="com.pickflair.mobile.android.CustomSplashScreenPlugin" /&gt;

CustomSplashScreen - will be name of plugin in js

after that you can call java code from js by executing:

PhoneGap.exec(null, null, 'CustomSplashScreen', 'hide', []);

And plugin will hide splashscreen and make visible webView container

Victor

**Comment by johnbran** [comment]
I hate to be such a pest but I am still having issues.  I believe it is because I am not properly importing the class (new platform ignorance)  Here is my xml.

<?xml version="1.0" encoding="utf-8"?>
<plugins>
    <plugin name="App" value="com.phonegap.App"/>
    <plugin name="Geolocation" value="com.phonegap.GeoBroker"/>
    <plugin name="Device" value="com.phonegap.Device"/>
    <plugin name="Accelerometer" value="com.phonegap.AccelListener"/>
    <plugin name="Compass" value="com.phonegap.CompassListener"/>
    <plugin name="Media" value="com.phonegap.AudioHandler"/>
    <plugin name="Camera" value="com.phonegap.CameraLauncher"/>
    <plugin name="Contacts" value="com.phonegap.ContactManager"/>
    <plugin name="Crypto" value="com.phonegap.CryptoHandler"/>
    <plugin name="File" value="com.phonegap.FileUtils"/>
    <plugin name="Network Status" value="com.phonegap.NetworkManager"/>
    <plugin name="Notification" value="com.phonegap.Notification"/>
    <plugin name="Storage" value="com.phonegap.Storage"/>
    <plugin name="Temperature" value="com.phonegap.TempListener"/>
    <plugin name="FileTransfer" value="com.phonegap.FileTransfer"/>
    <plugin name="Capture" value="com.phonegap.Capture"/>
    <plugin name="CustomSplashScreen" value="com.pickflair.mobile.android.CustomSplashScreenPlugin">
</plugin>
</plugins>

Here is my project .java file:
package com.android.passport;

import com.phonegap.*; 

import android.os.Bundle;

public class App extends DroidGap {
    /*\* Called when the activity is first created. */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        super.setIntegerProperty("loadUrlTimeoutValue", 60000);
        super.setIntegerProperty("splashscreen", R.drawable.splash);

```
    super.loadUrl("file:///android_asset/www/index.html");
}
```

}

yours:

package com.inetstd.android.phonegap.customsplashscreen.test;

import com.inetstd.android.phonegap.customsplashscreen.DroidGapWithCustomSplashScreen;
import com.inetstd.android.phonegap.customsplashscreen.R;

import android.content.Intent;

import android.os.Bundle;

public class LandingActivity extends DroidGapWithCustomSplashScreen {

```
/** Called when the activity is first created. */
@Override
public void onCreate(Bundle savedInstanceState) {       
    super.onCreate(savedInstanceState);             
    super.setIntegerProperty("loadUrlTimeoutValue", 60000);
    super.setIntegerProperty(C_CUSTOM_SPLASH_SCREEN, R.drawable.splash);        
    super.loadUrl("file:///android_asset/www/index.html");
}

@Override
protected void onTryAgain() {
    Intent i = new Intent(this, LandingActivity.class);
    i.setFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
    i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
    i.addFlags(Intent.FLAG_ACTIVITY_NO_ANIMATION);
    this.startActivity(i);
}   
```

}

If i try to import the file using something like : 
import com.pickflair.mobile.android.CustomSplashScreenPlugin 
it gives me the error cannot resolve com.pickflair

so I have a couple of questions.

With the plugin xml register you gave me, is it loading the .java files remotely of your server during compile? if so should they be local?
What am I missing as far as correctly importing this class? Like I said I am moving from xcode to eclipse so I am very new at this platform but I catch on quick.
Thanks for all your help.

**Comment by johnbran** [comment]
The site is not letting me post the xml code. so here it is without the formatting.  plugin name="CustomSplashScreen" value="com.pickflair.mobile.android.CustomSplashScreenPlugin"

**Comment by inetstd** [comment]
Sorry com.pickflair.*\* is my real project. I've just mixed up projects.

You need to point plugin name="CustomSplashScreen" to your CustomSplashScreenPlugin.java in case of this project it is:

com.inetstd.android.phonegap.customsplashscreen.CustomSplashScreenPlugin

Also you should extend activity from DroidGapWithCustomSplashScreen.

public class App extends DroidGapWithCustomSplashScreen ...

**Comment by johnbran** [comment]
Could you explain the declairation. In your project the file path (on my computer) is...
 C:\Users\John\workspace\phonegap-android-custom-splashscreen\src\com\inetstd\android\phonegap\customsplashscreen 
so it makes sense that the declaration in the xml is
com.inetstd.android.phonegap.customsplashscreen.CustomSplashScreenPhugin <-- notice the typo in the project

when I try to do the same with my project I get the error The import com.android.customsplashscreen cannot be resolved

here is my project path: C:\Users\John\workspace\Passport\src\com\android\customsplashscreen
plugin name="CustomSplashScreen" value="com.android.customsplashscreen.CustomSplashScreenPhugin"

what am I not getting?

**Comment by inetstd** [comment]
In java there are packages (namespaces). So you can't move file from one folder to another without fixing package declaration. If you move CustomSplashScreenPlugin.java check first line of file.

Thanks for noticing typo. I'll fix shortly.

**Comment by johnbran** [comment]
Hey, I got it working. Thanks for your help.  I did find an issue.  I noticed that splash screen pauses the app the amount of time that is placed in this line...super.setIntegerProperty("loadUrlTimeoutValue", 5000); After that time the app continues.  That isnt the real problem, it just causes my app about 10sec to load completely.  The issue is if I reduce the pause to less than 5000ms it gives me a 'no internet connection, please try again' message.  Why would this be?

**Comment by inetstd** [comment]
First of all if you are using internet - add permission to your manifest file.

loadUrlTimeoutValue is phonegap variable tells browser how long wait for page loading. If your internet connection is slow and page is loading more than loadUrlTimeoutValue no internet connection exception will be fired.

Actually this variable is not connected with splashscreen. In production I usually set it to 1 minute. If page will be loaded less than one minute - everything will be ok. So it is MAX time to wait
